import React from 'react';
import PageHeader from '../components/shared/PageHeader';
import SEO from '../components/SEO';

export default function ReferralProgram() {
  const faqItems = [
    {
      question: "How much commission can I earn?",
      answer: "You can earn up to 50% commission on your referrals' trading fees."
    },
    {
      question: "How are commissions paid?",
      answer: "Commissions are paid out automatically in the traded cryptocurrency."
    },
    {
      question: "Is there a limit to how many people I can refer?",
      answer: "No, there's no limit. Refer as many traders as you want and earn commission on all their trades."
    }
  ];

  const breadcrumbs = [
    { name: 'Home', item: '/' },
    { name: 'Referral Program', item: '/referral' }
  ];

  return (
    <div>
      <SEO 
        title="Referral Program | Earn 50% Commission | Odysey Exchange"
        description="Join Odysey Exchange's referral program and earn up to 50% commission on your referrals' trading fees. Start earning passive income today with our generous crypto referral program."
        canonicalUrl="/referral"
        keywords={[
          'crypto referral program',
          'trading commission',
          'passive income',
          'affiliate program',
          'crypto affiliate',
          'referral bonus',
          '50% commission'
        ]}
        faq={faqItems}
        breadcrumbs={breadcrumbs}
        videoUrl="https://odysey.fun/videos/referral-tutorial.mp4"
        structuredData={{
          '@context': 'https://schema.org',
          '@type': 'Product',
          name: 'Odysey Exchange Referral Program',
          description: 'Earn up to 50% commission on referrals',
          image: [
            'https://odysey.fun/images/referral-program-main.webp',
            'https://odysey.fun/images/referral-program-dashboard.webp'
          ],
          offers: {
            '@type': 'Offer',
            description: 'Up to 50% commission on trading fees',
            availability: 'https://schema.org/InStock',
            priceSpecification: {
              '@type': 'PriceSpecification',
              price: '0',
              priceCurrency: 'USD',
              description: 'Free to join. Earn up to 50% commission on referral trading fees.'
            }
          },
          aggregateRating: {
            '@type': 'AggregateRating',
            ratingValue: '4.9',
            reviewCount: '2150'
          },
          potentialAction: {
            '@type': 'JoinAction',
            name: 'Join Referral Program',
            url: 'https://odysey.fun/referral#join'
          }
        }}
      />
      <PageHeader
        title="Referral Program"
        description="Earn up to 50% commission on referral trading fees"
      />
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
        <div className="bg-white rounded-lg shadow-lg p-8">
          <h2 className="text-2xl font-semibold mb-4">How It Works</h2>
          <div className="space-y-6">
            <div>
              <h3 className="text-lg font-medium text-gray-900 mb-2">1. Share Your Link</h3>
              <p className="text-gray-600">Get your unique referral link and share it with friends and followers.</p>
            </div>
            <div>
              <h3 className="text-lg font-medium text-gray-900 mb-2">2. Friends Start Trading</h3>
              <p className="text-gray-600">When your referrals start trading, you'll earn commissions on their trading fees.</p>
            </div>
            <div>
              <h3 className="text-lg font-medium text-gray-900 mb-2">3. Earn Rewards</h3>
              <p className="text-gray-600">Receive up to 50% of the trading fees generated by your referrals.</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}