import React from 'react';
import PageHeader from '../components/shared/PageHeader';

export default function ReferralProgram() {
  return (
    <div>
      <PageHeader
        title="Referral Program"
        description="Earn up to 50% commission on referral trading fees"
      />
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
        <div className="bg-white rounded-lg shadow-lg p-8">
          <h2 className="text-2xl font-semibold mb-4">How It Works</h2>
          <div className="space-y-6">
            <div>
              <h3 className="text-lg font-medium text-gray-900 mb-2">1. Share Your Link</h3>
              <p className="text-gray-600">Get your unique referral link and share it with friends and followers.</p>
            </div>
            <div>
              <h3 className="text-lg font-medium text-gray-900 mb-2">2. Friends Start Trading</h3>
              <p className="text-gray-600">When your referrals start trading, you'll earn commissions on their trading fees.</p>
            </div>
            <div>
              <h3 className="text-lg font-medium text-gray-900 mb-2">3. Earn Rewards</h3>
              <p className="text-gray-600">Receive up to 50% of the trading fees generated by your referrals.</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}